// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PicPayment.Persistence.Context;

#nullable disable

namespace PicPayment.API.Migrations
{
    [DbContext(typeof(PicPaymentContext))]
    partial class PicPaymentContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PicPayment.Domain.Domains.Transferencia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataTransferencia")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("IdContaDestino")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdContaOrigem")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TipoTransferencia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Valor")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("IdContaDestino");

                    b.HasIndex("IdContaOrigem");

                    b.ToTable("Transferencias");
                });

            modelBuilder.Entity("PicPayment.Domain.Domains.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("CPF")
                        .HasColumnType("bigint");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("NomeCompleto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Saldo")
                        .HasColumnType("float");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Id", "CPF", "Email")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("PicPayment.Domain.Domains.Transferencia", b =>
                {
                    b.HasOne("PicPayment.Domain.Domains.Usuario", "ContaDestino")
                        .WithMany("TransferenciasDestino")
                        .HasForeignKey("IdContaDestino")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PicPayment.Domain.Domains.Usuario", "ContaOrigem")
                        .WithMany("TransferenciasOrigem")
                        .HasForeignKey("IdContaOrigem")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ContaDestino");

                    b.Navigation("ContaOrigem");
                });

            modelBuilder.Entity("PicPayment.Domain.Domains.Usuario", b =>
                {
                    b.Navigation("TransferenciasDestino");

                    b.Navigation("TransferenciasOrigem");
                });
#pragma warning restore 612, 618
        }
    }
}
